dist: xenial
language: java

addons:
  sonarcloud:
    organization: "josferde5"
    token:
      secure: lCNNUOUVU/UEC1Oipq9Dx0Utuy7ynQLlJPhQPKbynnQTysSZNxeItDaFAlkzfUDYdMUyEYyFb7Q7s2WsiynvFG7B7k70YmOmIBSN3zgoLiFVmizuHLFA0pQz3hOdITDlhm2rGEc37hXpNYnNoEXPhoNNznbr5GoSQ7oO6NORCesMLzq6AGKq3RQkw5abS0bIjFaYI7XAyh+MLWH764sFuVXSVjwj0R972dnmQPi6zm2D1rLs8mRTJLkSKR7W4i7/qECrTVM8wl/ih20V3/2JDALVSpIA/tBpMTShGCuA/GG2abf3/U1vKgqjsB7C/8zQtWY6suQKOr79Jb/ZbyQ38WhIRny7ube2aD695v6KnJjiiFEB9dk2XABYpURDD7BbwY/Ewlk/USMt/5JVxEWQA2MxubyRjJ8stpxK9fbFut3DDbC9Ux9v6bqk+s8y3GggCoaHimdAEsyFPvupDlUodsoRg5JbGww3irOkCxubV3Lgaa4oBKQ25tIXS0mUGS7MwrT/qgJmjxrw5mIbwI2T798JRugyA9LNcS4WJbgpY2FuRSovSmahBdXo7DwWerEOi/t7pPCRZ1tfQRssiIZAD4e8Jy5FjAZYlMNoHPn9RHH/gWhtbN1YUDQtxsXpVMhzbNVgybsgPTcFT/HbA0lrSO3UrB8pEhw85R5yCzqcY7Y=
before_install:
  - chmod +x scripts/install_dependencies.sh
install:
  - ./scripts/install_dependencies.sh
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=josferde5_IDLReasoner-choco-API